language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.0.0-p576
  - 2.2.2

env:
  - CHEF_VERSION=12.0.3

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.4.0-1_amd64.deb
  - sudo dpkg -i chefdk_0.4.0-1_amd64.deb
  - bundle install

script:
  - kitchen test
