language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.0.0-p576
  - 2.2.2

env:
  - CHEF_VERSION=12.0.3

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - sudo apt-get install chefdk
  - bundle install

script:
  - kitchen test
